@HOST = http://localhost:5039

###
# @name managers
# manager create account
POST {{HOST}}/managers/
Content-Type: application/json

{
  "name":"example",
  "email":"example@gmail.com",
  "password":"example"
}
###
GET {{HOST}}/managers/i HTTP/1.1
Content-Type: application/json

###
#
#
#
#
###

# @name auth
# manager login
POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
  "email":"example@gmail.com",
  "password":"example"
}
###
# select store
POST {{HOST}}/auth/select/7eb9a95d-a6e6-4165-9f7e-1e97b8d9166d HTTP/1.1
Content-Type: application/json

{
  "password": "example"
} 

###
#
#
#
#
###

# @name stores
# manager create a new store
POST {{HOST}}/stores HTTP/1.1
Content-Type: application/json

{
  "name" : "example"
}

###
# find all my stores
GET {{HOST}}/stores/my HTTP/1.1

###
GET {{HOST}}/stores/7eb9a95d-a6e6-4165-9f7e-1e97b8d9166d HTTP/1.1

###
#
#
#
#
###

# @name tables
POST {{HOST}}/tables HTTP/1.1
Content-Type: application/json

{
  "number": 1
}
###
GET {{HOST}}/tables/acaee29d-d92d-4475-8d0f-006935c4301d HTTP/1.1
###
DELETE {{HOST}}/tables/acaee29d-d92d-4475-8d0f-006935c4301d