@HOST = http://10.220.0.8:5039

###########################################
##                MANAGERS               ##
###########################################

#  CREATE ACCOUNT OF MANAGER
POST {{HOST}}/managers/
Content-Type: application/json

{
  "name":"example",
  "email":"example@gmail.com",
  "password":"example"
}

###
# GET INFORMATIONS OF MANAGER
GET {{HOST}}/managers/i HTTP/1.1
Content-Type: application/json

###########################################
##             AUTHENTICATION            ##
###########################################

# LOGIN OF MANAGER
POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
  "email":"example@gmail.com",
  "password":"example"
}

###
# AUTH ON STORE
POST {{HOST}}/auth/select/040e7abb-4c2c-45f2-a433-883eea9dff8d HTTP/1.1
Content-Type: application/json

{
  "password": "example"
} 

###########################################
##                 STORES                ##
###########################################

# CREATE A NEW STORE
POST {{HOST}}/stores HTTP/1.1
Content-Type: application/json

{
  "name" : "hamburgueria",
  "password": "example"
}

###
# GET ALL STORES
GET {{HOST}}/stores/my HTTP/1.1

###
# GET INFORMATIONS OF THE SPECIFIC STORE {STOREID}
GET {{HOST}}/stores/040e7abb-4c2c-45f2-a433-883eea9dff8d HTTP/1.1

###########################################
##                 TABLES                ##
###########################################

# CREATE A NEW STORE
POST {{HOST}}/tables HTTP/1.1
Content-Type: application/json

{
  "number": 2
} 

###
# GET ALL TABLES
GET {{HOST}}/tables HTTP/1.1

###
# DELETE TABLE                      {TABLEID}
DELETE {{HOST}}/tables/acaee29d-d92d-4475-8d0f-006935c4301d

###########################################
##               PRODUCTS                ##
###########################################

# GET ALL PRODUCTS
GET {{HOST}}/products HTTP/1.1

###
# GET ALL PRODUCTS
POST {{HOST}}/products HTTP/1.1
Content-Type: application/json

{
  "name": "PRODUTO 1",
  "description": "Descrição do produto",
  "price": 20.00
}

###########################################
##                ORDERS                 ##
###########################################

POST {{HOST}}/orders
Content-Type: application/json

{ 
  "tableId": "58e12f0f-45a1-427f-be96-954cda16c04b"
}

###
# GET ALL INFORMATIONS OF TABLE
GET {{HOST}}/orders/e4580179-7eb6-4d14-94d4-059f7caeb5d1

###
# GET ALL ORDERS
GET {{HOST}}/orders

###########################################
##            ORDERS-PRODUCTS            ##
###########################################

POST {{HOST}}/orders-products
Content-Type: application/json

{
  "quantity": 1,
  "orderId": "3e2b113b-2584-45e3-8b0e-592bf0f3076d",
  "productId": "1032900f-ae6e-4c00-b2cf-b04322f842f2",
  "options": []
}

###
# GET ALL ORDERS PRODUCTS OF STORE
GET {{HOST}}/orders-products

###
# UPDATE STATUS OF ORDER PRODUCT
PUT {{HOST}}/orders-products/status/f7027806-12db-444d-a776-a23d60060507
Content-Type: application/json

{ 
  "status": "DELIVERED"
}