@HOST = http://localhost:5039

###
# @name managers
# manager create account
POST {{HOST}}/managers/
Content-Type: application/json

{
  "name":"example",
  "email":"example@gmail.com",
  "password":"example"
}

###
# @name managers
GET {{HOST}}/managers/i HTTP/1.1
Content-Type: application/json

###
# @name auth
# manager login
POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
  "email":"example@gmail.com",
  "password":"example"
}

###
# @name store
# manager create a new store
POST {{HOST}}/stores HTTP/1.1
Content-Type: application/json

{
  "name" : "example5"
}

###
# @name auth
# select store
POST {{HOST}}/auth/select/e240662b-7f01-49f6-89f0-c0a87066083d HTTP/1.1
Content-Type: application/json

{
  "password": "example"
} 

###
# @name stores
# find all my stores
GET {{HOST}}/stores/my HTTP/1.1

###

GET {{HOST}}/stores/96eb3aee-3b34-4ae9-bbc1-9500dc2411fc HTTP/1.1