import { _COOKIE_ACCESS_TOKEN, _COOKIE_REFRESH_TOKEN } from "@/config/cookies";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Organizze",
  description: "Generated by create next app",
};

const SERVER_URL = process.env.NEXT_PUBLIC_API_URL;

export default async function Layout({ children }: LayoutProps) {
  const cookiesStore = await cookies();
  const accessToken = cookiesStore.get(_COOKIE_ACCESS_TOKEN)?.value;
  const refreshToken = cookiesStore.get(_COOKIE_REFRESH_TOKEN)?.value;

  try {
    const res = await fetch(`${SERVER_URL}/managers/i`, {
      credentials: "include",
      headers: {
        Cookie: `${_COOKIE_ACCESS_TOKEN}=${accessToken};${_COOKIE_REFRESH_TOKEN}=${refreshToken}`,
      },
    });

    const responseJSON = await res.json();

    if (responseJSON.email) {
      return children;
    }

    throw new Error();
  } catch (error: unknown) {
    console.log(error)
    redirect("/");
  }
}
