import type { Metadata } from "next";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { QueryProvider } from "@/providers/query-client-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body
        cz-shortcut-listen="false"
        className={`${geistSans.variable} ${geistMono.variable} text-neutral-700 dark:text-neutral-200 bg-gray-50 dark:bg-neutral-950 antialiased`}
      >
        <QueryProvider>{children}</QueryProvider>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
