import type { Metadata } from "next";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { QueryProvider } from "@/providers/query-client-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light" suppressHydrationWarning>
      <body
        cz-shortcut-listen="false"
        className={`text-gray-600 dark:text-neutral-200 flex flex-col bg-gray-200 dark:bg-neutral-950 p-0 2xl:p-4`}
      >
        <div className="rounded-none 2xl:rounded-xl overflow-hidden flex-1 flex shadow-xl">
          <QueryProvider>{children}</QueryProvider>
          <ToastContainer position="bottom-right" />
        </div>
      </body>
    </html>
  );
}
