
import { QueryProvider } from "@/providers/query-client-provider";
import type { Metadata } from "next";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light">
      <body
        className={`text-gray-600 dark:text-neutral-200 flex flex-col bg-zinc-200  dark:bg-neutral-950 p-0 2xl:p-4`}
      >
        <div className="rounded-none 2xl:rounded-2xl overflow-hidden flex-1 flex border">
          <QueryProvider>{children}</QueryProvider>
          <ToastContainer
            pauseOnHover={false}
            limit={1}
            rtl={false}
            autoClose={1000}
            transition={Slide}
            hideProgressBar={true}
            closeButton={false}
            position="top-center"
          />
        </div>
      </body>
    </html>
  );
}
